### ISSUE TITLE
Updating wallet

### ISSUE THREAD

**Issue by Dulcimer0909** [Crypto-toolbox/btfxwss#110]
Hello, 

I am trying the following. Any help would be appreciated.

I want to store my wallet in two variables but cant get it to do so. 

wallet = wss.wallets.get()
print(wallet)
newwallet = wss.wallets.get()
print(newwallet)

I can print the wallet without problem. But when the program arrives at new wallet, it hangs. Any suggestions?

Regards,
Dulcimer

**Comment by nlsdfnbch** [comment]
Hey @Dulcimer0909 ,
thanks for using my library! 

The reason this call is blocking is because there hasn't any data arrived on this channel after the last `get()` call. You can avoid this by passing `get(blocking=False)` - but beware that this returns `None` if there is no data available on the `Queue` object returned by `wss.wallets`.

**Comment by Dulcimer0909** [comment]
Thank you for your answer. A slight correction to your answer though.
get(blocking=False) is actually get(block=False).

Regards,
Dulcimer
